[versions]
apollo = "4.3.3"
kotlin = "2.2.10"
kotlinx-serialization = "1.9.0"
kotlinx-coroutines = "1.10.2"
okhttp = "5.1.0"
telegram-bot = "6.2.0"

[libraries]
apollo-gradlePlugin = { module = "com.apollographql.apollo:apollo-gradle-plugin", version.ref = "apollo" }
apollo-runtime = { module = "com.apollographql.apollo:apollo-runtime", version.ref = "apollo" }

kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-serializationPlugin = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }

kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }

okhttp-core = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-loggingInterceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
okhttp-mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okhttp" }

clikt = "com.github.ajalt.clikt:clikt:5.0.3"
ktoml = "com.akuleshov7:ktoml-core:0.7.1"
cardiologist = "io.github.kevincianfarini.cardiologist:cardiologist:0.8.0"
poko-gradlePlugin = "dev.drewhamilton.poko:poko-gradle-plugin:0.19.3"
buildConfig-gradlePlugin = "com.github.gmazzo:gradle-buildconfig-plugin:3.1.0"
telegram-bot = { module = "io.github.kotlin-telegram-bot.kotlin-telegram-bot:telegram", version.ref = "telegram-bot" }

junit = "junit:junit:4.13.2"
assertk = "com.willowtreeapps.assertk:assertk:0.28.1"
